version: 0.1.0-CI-{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
init:
  # Set "build version number" to "short-commit-hash" or when tagged to "tag name" (Travis style)
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true") {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      } else {
        Update-AppveyorBuild -Version "$env:version"
      }
build:
  publish_nuget: true
  publish_nuget_symbols: true
  parallel: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: TcozeAv6mvs3WmvMS6uH42TYFf1luFH7pJUTkNIJCIDU+zVivDLWv8u+dLvOnZus
  on:
    branch: master